actions:
    forward_action:
        primitives:
            - set_eth_dst
            - set_eth_src
            - output
            - dec_ttl
    controller_action:
        primitives:
            - notify
            - mark_to_drop
    drop_action:
        primitives:
            - mark_to_drop
tables:
    controller_table:
        matches:
            istd.ip_proto: all_or_exact
            hdr.tcp.source: all_or_exact
            hdr.tcp.destination: all_or_exact
            hdr.ipv4.destination: all_or_exact
        actions:
            - controller_action
    termination_table:
        matches:
            hdr.ethernet.destination: exact
        actions: []
    routing_table_v4:
        matches:
            hdr.ipv4.destination: lpm
        actions:
            - forward_action
            - drop_action
    routing_table_v6:
        matches:
            hdr.ipv6.destination: lpm
        actions:
            - forward_action
            - drop_action
pipeline:
  - controller_module:
    - type: table
      table: controller_table
  - router_module:
    - type: table
      table: termination_table
      iftrue:
        - type: conditional
          field: istd.ethertype
          value: 0x86dd
          iftrue:
            - type: table
              table: routing_table_v6
          iffalse:
            - type: conditional
              field: istd.ethertype
              value: 0x800
              iftrue:
                  - type: table
                    table: routing_table_v4
