actions:
    count_action:
        primitives:
            - output
    proactive_action:
        primitives:
            - output
            - clone
    default_action:
        primitives:
            - output

tables:
    reactive_table:
        matches:
            istd.ethertype: exact
            hdr.ipv6.source: all_or_exact
            hdr.ipv6.destination: all_or_exact
            hdr.ipv4.source: all_or_exact
            hdr.ipv4.destination: all_or_exact
            istd.ip_proto: exact
            hdr.tcp.source: all_or_exact
            hdr.tcp.destination: all_or_exact
            hdr.udp.source: all_or_exact
            hdr.udp.destination: all_or_exact
        actions:
            - count_action
    proactive_table:
        matches:
            istd.ingress_port: all_or_exact
            istd.ip_proto: all_or_exact
        actions:
            - proactive_action
    default_table:
        matches:
            istd.ingress_port: all_or_exact
        actions:
            - default_action
pipeline:
    - module:
        - type: table
          table: reactive_table
          iffalse:
            - type: table
              table: proactive_table
              iffalse:
                - type: table
                  table: default_table

