actions:
    telekinesis_action:
        primitives:
            - set_eth_dst
            - set_eth_src
            - set_vid
            - dec_ttl
            - output
    bpdu_action:
        primitives:
            - notify

tables:
    telekinesis_table_v4:
        matches:
            hdr.ipv4.destination: lpm
        actions:
            - telekinesis_action
    telekinesis_table_v6:
        matches:
            hdr.ipv6.destination: lpm
        actions:
            - telekinesis_action
    bpdu_table:
        matches:
            hdr.ethernet.destination: all_or_exact
        actions:
            - bpdu_action
    termination:
        matches:
            hdr.ethernet.destination: exact
        actions: []
pipeline:
    - module:
        - type: table
          table: termination
          iftrue:
            - type: conditional
              field: istd.ethertype
              value: 0x86dd
              iftrue:
                - type: table
                  table: telekinesis_table_v6
              iffalse:
                - type: conditional
                  field: istd.ethertype
                  value: 0x800
                  iftrue:
                    - type: table
                      table: telekinesis_table_v4
        - type: table
          table: bpdu_table
