actions:
    multicast_action:
        primitives:
            - multicast
tables:
    paxos_table:
        matches:
            istd.ingress_port: all_or_exact
            hdr.ipv6.destination: ternary
        action:
            - multicast_action
pipeline:
    - module:
        - type: table
          table: paxos_table
