actions:
    notify_action:
        primitives:
            - notify
    drop_action:
        primitives:
            - mark_to_drop
tables:
    lldp_table:
        matches:
            istd.ingress_port: all_or_exact
            istd.ethertype: all_or_exact
        actions:
            - notify_action
            - drop_action
pipeline:
    - module:
        - type: table
          table: lldp_table
