actions:
    output_action:
        primitives:
            - output
    drop_action:
        primitives:
            - mark_to_drop
tables:
    table:
        matches:
            istd.ingress_port: all_or_exact
            hdr.vlan.vid: all_or_exact
        actions:
            - output_action
            - drop_action
pipeline:
    - module:
        - type: table
          table: table
