actions:
    unicast_action:
        primitives:
            - output
tables:
    reactive_table:
        matches:
            hdr.ethernet.source: all_or_exact
            hdr.ethernet.destination: all_or_exact
            istd.ethertype: all_or_exact
            hdr.vlan.vid: all_or_exact
            hdr.vlan.pcp: all_or_exact
            hdr.ipv4.source: all_or_exact
            hdr.ipv4.destination: all_or_exact
            istd.ip_proto: all_or_exact
            hdr.ipv4.dscp: all_or_exact
            hdr.ipv4.ecn: all_or_exact
        actions:
            - unicast_action
pipeline:
    - module:
        - type: table
          table: reactive_table
