actions:
    notify_action:
        primitives:
            - notify
    mapping_action:
        primitives:
            - set_ipv4_dst
            - set_eth_dst
            - output
    reverse_mapping_action:
        primitives:
            - set_eth_dst
            - set_ipv4_src
            - output

tables:
    pbr_table:
        matches:
            istd.ingress_port: all_or_exact
            hdr.ipv4.source: ternary
            hdr.ipv4.destination: all_or_exact
            hdr.tcp.destination: all_or_exact
            hdr.tcp.source: all_or_exact
        actions:
            - notify_action
            - mapping_action
            - reverse_mapping_action
pipeline:
    - module:
        - type: table
          table: pbr_table
