actions:
    tunnel_action:
        primitives:
            - output
    stripping_action:
        primitives:
            - pop_vlan
    remediation_action:
        primitives:
            - mark_to_drop
    redirect_action:
        primitives:
            - push_vlan
            - output
    mirror_action:
        primitives:
            - clone
tables:
    tunnel:
        matches:
            hdr.vlan.vid: all_or_exact
        actions:
            - tunnel_action
    stripping:
        matches:
            hdr.vlan.vid: all_or_exact
        actions:
            - stripping_action
    remediation_v4:
        matches:
            hdr.ethernet.source: all_or_exact
            hdr.ethernet.destination: all_or_exact
            istd.ethertype: all_or_exact
            hdr.ipv4.source: ternary
            hdr.ipv4.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.tcp.source: all_or_exact
            hdr.tcp.destination: all_or_exact
        actions:
            - remediation_action
    remediation_v6:
        matches:
            hdr.ethernet.source: all_or_exact
            hdr.ethernet.destination: all_or_exact
            istd.ethertype: all_or_exact
            hdr.ipv6.source: ternary
            hdr.ipv6.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.tcp.source: all_or_exact
            hdr.tcp.destination: all_or_exact
        actions:
            - remediation_action
    ipfix_v4:
        matches:
            hdr.ethernet.source: all_or_exact
            hdr.ethernet.destination: all_or_exact
            istd.ethertype: all_or_exact
            hdr.ipv4.source: ternary
            hdr.ipv4.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.tcp.source: all_or_exact
            hdr.tcp.destination: all_or_exact
        actions:
            - mirror_action
    ipfix_v6:
        matches:
            hdr.ethernet.source: all_or_exact
            hdr.ethernet.destination: all_or_exact
            istd.ethertype: all_or_exact
            hdr.ipv6.source: ternary
            hdr.ipv6.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.tcp.source: all_or_exact
            hdr.tcp.destination: all_or_exact
        actions:
            - mirror_action
pipeline:
    - tunnel_module:
        - type: table
          table: tunnel
    - stripping_module:
        - type: table
          table: stripping
    - ipfix_module:
        - type: conditional
          field: istd.ethertype
          value: 0x86dd
          iftrue:
            - type: table
              table: remediation_v6
              iffalse:
                - type: table
                  table: ipfix_v6
          iffalse:
            - type: conditional
              value: 0x800
              field: istd.ethertype
              iftrue:
                - type: table
                  table: remediation_v4
                  iffalse:
                    - type: table
                      table: ipfix_v4
