actions:
    local_delivery:
        primitives:
            - output
            - set_eth_src
            - set_eth_dst
            - set_vid
            - dec_ttl
    ingress:
        primitives:
            - push_mpls
            - set_eth_dst
            - set_eth_src
            - output
    egress:
        primitives:
            - pop_mpls
            - output
            - set_eth_src
            - set_eth_dst
            - dec_ttl
tables:
    termination:
        matches:
            hdr.ethernet.destination: exact
        actions: []
    ingress:
        matches:
            istd.ingress_port: all_or_exact
            hdr.ethernet.destination: all_or_exact
            hdr.ipv6.source: ternary
            hdr.ipv6.destination: ternary
        actions:
            - local_delivery
            - ingress
    mpls_termination:
        matches:
            hdr.ethernet.destination: exact
        actions: []
    egress_mpls:
        matches:
            hdr.mpls.label: exact
        actions:
            - egress
pipeline:
    - egress:
        - type: conditional
          field: istd.ethertype
          value: 0x8847
          iftrue:
            - type: table
              table: mpls_termination
              iftrue:
                - type: table
                  table: egress_mpls
    - ingress:
        - type: conditional
          field: istd.ethertype
          value: 0x86dd
          iftrue:
            - type: table
              table: ingress
