actions:
    drop_action:
        primitives:
            - mark_to_drop
    #set_vid_untagged_action:
    #    primitives:
    #        - push_vlan
    set_vid_action:
        primitives:
            - set_vid
    notify_action:
        primitives:
            - notify
    multicast_action:
        primitives:
            - multicast
    learn_mac_action:
        primitives:
            - notify
    forward_action:
        primitives:
            - output
    untagged_packet_action:
        primitives:
            - pop_vlan
    set_eth_src_action:
        primitives:
            - set_eth_src
    set_eth_dst_action:
        primitives:
            - set_eth_dst
    unknown_unicast_action:
        primitives:
            - multicast
    erif_bridge_action:
        primitives:
            - dec_ttl
    erif_action:
        primitives:
            - dec_ttl
            - output
    nh_action:
        primitives:
            - set_eth_dst
    l3_interface_action:
        primitives:
            - set_eth_src
            - set_vid
    neigh_action:
        primitives:
            - notify
    clone_action:
        primitives:
            - clone


tables:
    accepted_frame_type:
        matches:
            istd.recirculation: configured_any
            istd.ingress_port: exact
            istd.is_tagged: exact
        actions:
            - drop_action
            - set_vid_action

    acl_trap_table:
        # ACLs based on Broadcom
        matches:
            istd.ingress_port: all_or_exact
            istd.recirculation: all_or_exact
            hdr.ethernet.source: ternary
            hdr.ethernet.destination: ternary
            istd.ethertype: all_or_exact
            hdr.vlan.vid: ternary
            hdr.vlan.pcp: all_or_exact
            hdr.vlan.dei: all_or_exact
            istd.vrf: all_or_exact
            hdr.ipv4.source: ternary
            hdr.ipv4.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.ipv4.dscp: all_or_exact
            hdr.ipv4.ecn: all_or_exact
            hdr.arp.spa: ternary
            hdr.ipv6.source: ternary
            hdr.ipv6.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.ipv6.flow_label: ternary
            hdr.ipv6.dscp: all_or_exact
            hdr.ipv6.ecn: all_or_exact
            hdr.tcp.source: configured_any
            hdr.tcp.destination: configured_any
            hdr.udp.source: configured_any
            hdr.udp.destination: configured_any
        actions:
            - set_eth_src_action
            - set_eth_dst_action
            - set_vid_action
            - erif_action
            - erif_bridge_action
            - forward_action
            - drop_action
            - notify_action
            - multicast_action
            - untagged_packet_action
            - clone_action

    ingress_vlan_filtering_and_xstp:
        matches:
            istd.recirculation: configured_any
            istd.ingress_port: all_or_exact
            istd.is_tagged: all_or_exact
            hdr.vlan.vid: all_or_exact
        actions:
            - drop_action
            - set_vid_action

    learning_fdb:
        matches:
            istd.recirculation: configured_any
            istd.ingress_port: exact
            hdr.ethernet.source: exact
            hdr.vlan.vid: exact
        actions:
            - learn_mac_action

    l3_interface:
        matches:
            istd.recirculation: configured_any
            hdr.ethernet.destination: exact
            hdr.vlan.vid: all_or_exact
        actions: []

    fdb:
        matches:
            hdr.vlan.vid: exact
            hdr.ethernet.destination: exact
        actions:
            - forward_action
            - untagged_packet_action

    unknown_unicast:
        matches:
            hdr.vlan.vid: exact
        actions:
            - unknown_unicast_action

    egress_acl:
        matches:
            istd.ingress_port: all_or_exact
            istd.egress_port: all_or_exact
            istd.recirculation: all_or_exact
            hdr.ethernet.source: ternary
            hdr.ethernet.destination: ternary
            istd.ethertype: all_or_exact
            hdr.vlan.vid: ternary
            hdr.vlan.pcp: all_or_exact
            hdr.vlan.dei: all_or_exact
            istd.vrf: all_or_exact
            hdr.ipv4.source: ternary
            hdr.ipv4.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.ipv4.dscp: all_or_exact
            hdr.ipv4.ecn: all_or_exact
            hdr.arp.spa: ternary
            hdr.ipv6.source: ternary
            hdr.ipv6.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.ipv6.flow_label: ternary
            hdr.ipv6.dscp: all_or_exact
            hdr.ipv6.ecn: all_or_exact
            hdr.tcp.source: configured_any
            hdr.tcp.destination: configured_any
            hdr.udp.source: configured_any
            hdr.udp.destination: configured_any
        actions:
            - set_eth_src_action
            - set_eth_dst_action
            - forward_action
            - drop_action
            - notify_action
            - multicast_action

    ingress_l3_interface:
        matches:
            hdr.vlan.vid: exact
            istd.ingress_port: exact
        actions:
            - drop_action

    l3_interface_acl:
        matches:
            istd.ingress_port: all_or_exact
            istd.recirculation: all_or_exact
            hdr.ethernet.source: ternary
            hdr.ethernet.destination: ternary
            istd.ethertype: all_or_exact
            hdr.vlan.vid: ternary
            hdr.vlan.pcp: all_or_exact
            hdr.vlan.dei: all_or_exact
            istd.vrf: all_or_exact
            hdr.ipv4.source: ternary
            hdr.ipv4.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.ipv4.dscp: all_or_exact
            hdr.ipv4.ecn: all_or_exact
            hdr.arp.spa: ternary
            hdr.ipv6.source: ternary
            hdr.ipv6.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.ipv6.flow_label: ternary
            hdr.ipv6.dscp: all_or_exact
            hdr.ipv6.ecn: all_or_exact
            hdr.tcp.source: configured_any
            hdr.tcp.destination: configured_any
            hdr.udp.source: configured_any
            hdr.udp.destination: configured_any
        actions:
            - set_eth_src_action
            - set_eth_dst_action
            - forward_action
            - drop_action
            - notify_action
            - multicast_action

    router_v4:
        matches:
            istd.recirculation: configured_any
            hdr.ipv4.destination: lpm
        actions:
            - nh_action
            - erif_action
            - erif_bridge_action
            - l3_interface_action
            - neigh_action
            - set_eth_src_action
            - set_eth_dst_action
            - forward_action
            - drop_action

    router_v6:
        matches:
            istd.recirculation: configured_any
            hdr.ipv6.destination: lpm
        actions:
            - nh_action
            - erif_action
            - erif_bridge_action
            - l3_interface_action
            - neigh_action
            - set_eth_src_action
            - set_eth_dst_action
            - forward_action
            - drop_action

    egress_l3_interface_acl:
        matches:
            istd.ingress_port: all_or_exact
            istd.recirculation: all_or_exact
            hdr.ethernet.source: ternary
            hdr.ethernet.destination: ternary
            istd.ethertype: all_or_exact
            hdr.vlan.vid: ternary
            hdr.vlan.pcp: all_or_exact
            hdr.vlan.dei: all_or_exact
            istd.vrf: all_or_exact
            hdr.ipv4.source: ternary
            hdr.ipv4.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.ipv4.dscp: all_or_exact
            hdr.ipv4.ecn: all_or_exact
            hdr.arp.spa: ternary
            hdr.ipv6.source: ternary
            hdr.ipv6.destination: ternary
            istd.ip_proto: all_or_exact
            hdr.ipv6.flow_label: ternary
            hdr.ipv6.dscp: all_or_exact
            hdr.ipv6.ecn: all_or_exact
            hdr.tcp.source: configured_any
            hdr.tcp.destination: configured_any
            hdr.udp.source: configured_any
            hdr.udp.destination: configured_any
        actions:
            - set_eth_src_action
            - set_eth_dst_action
            - forward_action
            - drop_action
            - notify_action
            - multicast_action

pipeline:
    - ingress_module:
        - type: table
          table: accepted_frame_type
        - type: table
          table: acl_trap_table

    - vlan_filtering_module:
        - type: table
          table: ingress_vlan_filtering_and_xstp

    - l3_module:
        - type: table
          table: l3_interface
          iftrue:
            - type: table
              table: l3_interface_acl
            - type: conditional
              field: istd.ethertype
              value: 0x86dd
              iftrue:
                - type: table
                  table: router_v6
              iffalse:
                - type: conditional
                  field: istd.ethertype
                  value: 0x800
                  iftrue:
                    - type: table
                      table: router_v4
        - type: table
          table: learning_fdb

    - l2_module:
        - type: table
          table: fdb
          iffalse:
            - type: table
              table: unknown_unicast
